//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetquizing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uetquizingEntities : DbContext
    {
        public uetquizingEntities()
            : base("name=uetquizingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<quizze> quizzes { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<QuizVariation> QuizVariations { get; set; }
        public virtual DbSet<quizQuestion> quizQuestions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<studentQuizze> studentQuizzes { get; set; }
        public virtual DbSet<studentMark> studentMarks { get; set; }
    }
}
