//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetquizing
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizVariation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizVariation()
        {
            this.quizQuestions = new HashSet<quizQuestion>();
        }
    
        public int variation_id { get; set; }
        public Nullable<int> quiz_id { get; set; }
        public string variation_title { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    
        public virtual quizze quizze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quizQuestion> quizQuestions { get; set; }
    }
}
