//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetquizing
{
    using System;
    using System.Collections.Generic;
    
    public partial class quizQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quizQuestion()
        {
            this.studentMarks = new HashSet<studentMark>();
        }
    
        public int id { get; set; }
        public Nullable<int> variation_id { get; set; }
        public Nullable<int> question_id { get; set; }
    
        public virtual question question { get; set; }
        public virtual QuizVariation QuizVariation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentMark> studentMarks { get; set; }
    }
}
