//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetquizing
{
    using System;
    using System.Collections.Generic;
    
    public partial class quizze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quizze()
        {
            this.QuizVariations = new HashSet<QuizVariation>();
            this.studentQuizzes = new HashSet<studentQuizze>();
            this.studentMarks = new HashSet<studentMark>();
        }
    
        public int quiz_id { get; set; }
        public string quiz_title { get; set; }
        public Nullable<double> total_marks { get; set; }
        public Nullable<int> total_questions { get; set; }
        public Nullable<double> marks_per_question { get; set; }
        public string teacher_id { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizVariation> QuizVariations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentQuizze> studentQuizzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentMark> studentMarks { get; set; }
    }
}
