//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uetquizing
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentQuizze
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public Nullable<int> quiz_id { get; set; }
        public Nullable<System.DateTime> attempted_on { get; set; }
        public Nullable<double> marks { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual quizze quizze { get; set; }
    }
}
